name: Render Disponibilités vélos dans Montpellier

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"  # Toutes les 15 minutes

jobs:
  render-dispo:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - name: Render Dispo.html
        run: quarto render dispo.qmd  --output-dir docs/

      - name: Deploy dispo.html to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/dispo.html 
          publish_branch: gh-pages
